version: '3'

services:
  mysql:
    image: ce19f003/mysql:5.7
    container_name: mysql-db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "dkdltm123"
    ports:
      - 3306:3306
    networks:
      - msa-network
    volumes:
      - "./init:/docker-entrypoint-initdb.d/"

  config:
    image: qpdh1924/testcontainer:v2
    depends_on:
      - mysql
    restart: on-failure
    environment:
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true"
      MYSQL_ROOT_PASSWORD: "dkdltm123"
    ports:
      - 8888:8888
    networks:
      - msa-network

  registry:
    image: ce19f003/registry
    depends_on:
      - config
      - mysql
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
    ports:
      - 8761:8761
    networks:
      - msa-network

  gateway:
    image: ce19f003/gateway
    depends_on:
      - config
      - registry
      - mysql
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true"
      MYSQL_ROOT_PASSWORD: "dkdltm123"
    ports:
      - 8080:8080
    networks:
      - msa-network

  auth:
    image: ce19f003/auth
    depends_on:
      - config
      - registry
      - mysql
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true"
      MYSQL_ROOT_PASSWORD: "dkdltm123"
      JWT_SECRET_KEY: "geunyoung_jwt_secret"
    ports:
      - 8081:8080
    networks:
      - msa-network

  diet:
    image: ce19f003/diet
    depends_on:
      - config
      - registry
      - mysql
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true"
      MYSQL_ROOT_PASSWORD: "dkdltm123"
    ports:
      - 8082:8080
    networks:
      - msa-network

  exercise:
    image: ce19f003/exercise
    depends_on:
      - config
      - registry
      - mysql
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true"
      MYSQL_ROOT_PASSWORD: "dkdltm123"
    ports:
      - 8083:8080
    networks:
      - msa-network

  statistics:
    image: ce19f003/statistics
    depends_on:
      - config
      - registry
      - mysql
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true"
      MYSQL_ROOT_PASSWORD: "dkdltm123"
    ports:
      - 8084:8080
    networks:
      - msa-network

networks:
  msa-network:
    external: true
