version: '3'
###################################################
# healthcheck 안에 있는 주소는 자신의 주소로 바꿔야 함   #
# front를 컨테이너 화 할 경우 컨테이너 명으로 curl 요청  #
# 30 초마다 웹 서버가 10초 이내에                     #
# 기본 페이지를 제공하는 확인                         #
# 최대 3번 재시도 함                                #
##################################################
services:
  mysql:
    image: ce19f003/mysql
    container_name: mysql-db
    restart: on-failure
    ports:
      - 3306:3306
    networks:
      - msa-network
    volumes:
      - "./init:/docker-entrypoint-initdb.d/"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://host.docker.internal:8000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  config:
    image: ce19f003/config
    container_name: config
    depends_on:
      - mysql
    restart: on-failure
    environment:
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true"
      MYSQL_ROOT_PASSWORD: "ce19f003"
    ports:
      - 8888:8888
    networks:
      - msa-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://host.docker.internal:8000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  registry:
    image: ce19f003/registry
    container_name: registry

    depends_on:
      - config
      - mysql
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
    ports:
      - 8761:8761
    networks:
      - msa-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://host.docker.internal:8000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  gateway:
    image: ce19f003/gateway
    container_name: gateway
    depends_on:
      - config
      - registry
      - mysql
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true"
      MYSQL_ROOT_PASSWORD: "ce19f003"
    ports:
      - 8080:8080
    networks:
      - msa-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://host.docker.internal:8000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  auth:
    image: ce19f003/auth
    container_name: auth
    depends_on:
      - config
      - registry
      - mysql
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true"
      MYSQL_ROOT_PASSWORD: "ce19f003"
      JWT_SECRET_KEY: "kimgyun_jwt_secret"
    ports:
      - 8081:8080
    networks:
      - msa-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://host.docker.internal:8000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  diet:
    image: ce19f003/diet
    container_name: diet
    depends_on:
      - config
      - registry
      - mysql
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true"
      MYSQL_ROOT_PASSWORD: "ce19f003"
    ports:
      - 8082:8080
    networks:
      - msa-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://host.docker.internal:8000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  exercise:
    image: ce19f003/exercise
    container_name: exercise
    depends_on:
      - config
      - registry
      - mysql
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true"
      MYSQL_ROOT_PASSWORD: "ce19f003"
    ports:
      - 8083:8080
    networks:
      - msa-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://host.docker.internal:8000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  statistics:
    image: ce19f003/statistics_no_cb
    # image: ce19f003/statistics
    container_name: statistics
    depends_on:
      - config
      - registry
      - mysql
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://config:8888"
      EUREKA_SERVER_URI: "http://registry:8761/eureka"
      MYSQL_CONNECTION_URI: "jdbc:mysql://mysql:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnection=true"
      MYSQL_ROOT_PASSWORD: "ce19f003"
    ports:
      - 8084:8080
    networks:
      - msa-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://host.docker.internal:8000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: on-failure
    ports:
      - 9090:9090
    networks:
      - msa-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml #writeBy 최혜민
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://host.docker.internal:8000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: on-failure
    ports:
      - 3000:3000
    networks:
      - msa-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://host.docker.internal:8000" ]
      interval: 30s
      timeout: 10s
      retries: 3


  alertmanager: #writeBy 최혜민
    image: prom/alertmanager
    user: root
    ports:
    - "9093:9093"
    volumes:
    - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
    - msa-network

  front:
    image: ce19f003/front
    container_name: front
    restart: on-failure
    ports:
      - 8000:80
    networks:
      - msa-network

networks:
  msa-network:
    external: true
